### ISSUE TITLE
Only one blogpost is shown on the mainpage after activating OGFileManager

### ISSUE THREAD

**Issue by anjog** [HarleyDavidson86/OGFileManager#2]
The last 10 rows of the html source code:

            
            
            
            
          </header>
        </div>
      </article>
    
      
      <article id="post-1" class="post-1 post type-post status-publish format-standard hentry category-1" itemtype="https://schema.org/CreativeWork" itemscope>
        <div class="inside-article">

          <header class="entry-header">

            

As you can see, the html source code for the 2nd blogpost starts but is cut off while iterating over the activated plugins. After switching off the OGFileManager plugin everthing works as expected. Digging around a litte the solution for me is to extend the function "pageBegin()" in the file "plugin.php" by inserting the following if-statement: 

    public function pageBegin() {
        global $page, $WHERE_AM_I;
        //Replace Patterns with links
        if ($WHERE_AM_I==='page') {
            $page->setField('content', $this->replaceLinks($page->content()));
        }
    }

Hope that helps.

**Comment by HarleyDavidson86** [comment]
Thanks, this seems legit, I will add this.
